### ISSUE TITLE
Missing elm-package.json file and/or update to 0.18?

### ISSUE THREAD

**Issue by charukiewicz** [mdgriffith/elm-skimmer#2]
Hello.  Let me preface by saying I really like this project and find myself using elm-skimmer.com frequently to find packages for particular functionality (e.g. searching for things like "table" or "animation").  I like the way that the search works / listing works and it allows me to find what I am looking for very quickly.

I tried cloning this repository today in order to create a PR for 0.18 but realize that there is no `elm-package.json` file.  This means I cannot run the `elm-upgrade` utility and would have to downgrade my `elm` installation back to 0.17 just to do an initial build of the project.

I would appreciate it if you could commit the `elm-package.json` file so that the project becomes buildable/upgradeable.  Perhaps build instructions would be helpful as well, as it looks like you have to run the python file in the `/data` directory to update the package list.

**Comment by mdgriffith** [comment]
Whoops, elm-package got left out when I was trying to gitignore the json data files :)  I've added it back in!

Let me know if you run into any issues.

**Comment by mdgriffith** [comment]
And I'm glad you like the project!
